Draft: Integration Testing
awslabs/aws-ddk pull request #235
Opened 2023-01-27 20:51 UTC by malachi-constant

Closes #164 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-27 21:54 UTC, malachi-constant commented
Interesting that `yarn.lock` update is no longer complaining. RE: #232 @LeonLuttenberger

2023-01-30 20:00 UTC, LeonLuttenberger requested changes
Overrall looks good! I think this is a good approach.

I wonder if we can make this run as part of our GitHub workflow somehow.

2023-01-30 20:36 UTC, malachi-constant commented on integ/integ.s3-event.ts
> +import * as integration from "@aws-cdk/integ-tests-alpha";
Thanks

2023-01-30 20:36 UTC, malachi-constant commented on integ/integ.kinesis-s3-stage.test.ts
> +      },
Good catch, updated

2023-01-31 16:43 UTC, LeonLuttenberger approved these changes

2023-01-31 16:49 UTC, merged